Master
BrightLocal/ApiDocs pull request #30
Opened 2016-10-06 15:56 UTC by HananeMoshe

Added php wrapper examples for all  client methods. As well as Json example response for for fetch reviews with businss data.

2016-10-06 16:05 UTC, ejeliot requested changes

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +$client = $api->post('v1/clients-and-locations/clients/'. $id.);
Additional "." after $id. Also, perhaps call the variable $clientId rather than $id to emphasise what it is.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +$success = $api->delete('v1/clients-and-locations/clients/' .$clientId.);
Extra "." after $clientId

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +<h3>Query Parameters</h3>
Any reason for switching heading format. ### seems more universal to me.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +> Search for a client
Header missing.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +echo 'Successfully deleted client.' . PHP_EOL;
Add indentation.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +
Remove additional line break.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +
Remove additional line break.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +
Remove line break.

2016-10-06 16:05 UTC, ejeliot commented on source/includes/_clients.md
> +
Remove line break.

2016-10-06 19:41 UTC, ejeliot requested changes

2016-10-06 19:41 UTC, ejeliot commented on source/includes/_clients.md
> +curl -X PUT \
This won't work. You need to also pass the API secret and expiry.

-d 'sig=\<INSERT_API_SIG\>' \
-d 'expires=\<INSERT_API_EXPIRES\>' \

Also indentation seems a little out on parameters. We're using spaces in files. Are you using tabs perhaps?

2016-10-06 19:41 UTC, ejeliot commented on source/includes/_clients.md
> +$success = $api->put('v1/clients-and-locations/clients/', array(
Let's show short array syntax [] rather than array(). It's supported in all but very old versions of PHP.

2016-10-06 19:41 UTC, ejeliot commented on source/includes/_clients.md
> +curl -X DELETE 'https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/:<INSERT_CLIENT_ID>?api-key=<INSERT_API_KEY>'
As above re signature and expires.

2016-10-06 19:41 UTC, ejeliot commented on source/includes/_clients.md
> +curl 'https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/:<INSERT_CLIENT_ID>?api-key=<INSERT_API_KEY>'
As above re sig and expires.

2016-10-06 19:41 UTC, ejeliot commented on source/includes/_clients.md
> +curl -X GET \
As above re sig and expires.

2016-10-06 21:20 UTC, ejeliot requested changes

2016-10-06 21:20 UTC, ejeliot commented on source/includes/_clients.md
> +curl -X DELETE 'https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/:<INSERT_CLIENT_ID>?api-key=<INSERT_API_KEY>&sig=<INSERT_API_SIG>&expires=<INSERT_API_EXPIRES>'
Remove :

2016-10-06 21:20 UTC, ejeliot commented on source/includes/_clients.md
> +curl 'https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/:<INSERT_CLIENT_ID>?api-key=<INSERT_API_KEY>&sig=<INSERT_API_SIG>&expires=<INSERT_API_EXPIRES>'
Remove :

2016-10-06 21:20 UTC, ejeliot commented on source/includes/_clients.md
> + -d 'q=<INSERT_SEARCH_QUERY>' \
-d 'q=My+Sample+Query' \

2016-10-06 21:30 UTC, HananeMoshe commented on source/includes/_clients.md
> +curl 'https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/:<INSERT_CLIENT_ID>?api-key=<INSERT_API_KEY>&sig=<INSERT_API_SIG>&expires=<INSERT_API_EXPIRES>'
Should I just remove these? Or should I replace them with a full curl request like below? For now I removed them. 
curl -X DELETE \
 -d 'api-key=<INSERT_API_KEY>' \
 -d 'sig=<INSERT_API_SIG>' \
 -d 'expires=<INSERT_API_EXPIRES>' \
 -d 'client-id=1' \ 
  https://tools.brightlocal.com/seo-tools/api/v1/clients-and-locations/clients/

2016-10-07 13:02 UTC, ejeliot approved these changes

2016-10-07 13:02 UTC, merged