GMB-55 API Doc- Update 'Location' API documentation to match the new validation rules
BrightLocal/ApiDocs pull request #62
Opened 2017-02-09 15:39 UTC by anrybalova

2017-02-09 19:24 UTC, judgedim approved these changes

2017-02-10 15:06 UTC, ejeliot approved these changes

2017-02-15 10:47 UTC, ejeliot requested changes

2017-02-15 10:47 UTC, ejeliot commented on source/includes/_locations.md
> +    'email_addresses' 	   => ['test@lebernardin.com'],
Please explain what these fields are for. Also, it looks like other fields use hyphens as separators. For consistency (if these are new fields) these should also use hyphens.

2017-02-15 14:29 UTC, ejeliot approved these changes

2017-02-17 10:09 UTC, merged