API-49 add endpoint that will return all supported directories
BrightLocal/ApiDocs pull request #72
Opened 2017-05-30 12:30 UTC by alnarozhny

2017-05-30 14:47 UTC, ejeliot requested changes

2017-05-30 14:47 UTC, ejeliot commented on source/includes/_appendix.md
> +We no longer list the supported local directories here. We now have an below which enables you to retrieve a list of directories either all or for an individual country (See list of Supported Countri
We now have an API method (shown below) that enables you to retrieve a list of directories for all supported countries.

2017-05-30 14:47 UTC, ejeliot commented on source/includes/_appendix.md
> + https://tools.brightlocal.com/seo-tools/api/v2/get-directories
/seo-tools/api/v1/directories/all
/seo-tools/api/v1/directories/\<country\>

2017-05-31 10:35 UTC, ejeliot approved these changes

2017-06-19 13:42 UTC, redhatua requested changes

2017-06-19 13:42 UTC, redhatua commented on source/includes/_appendix.md
> +$success = $api->post('v1/directories/all');
Should be GET

2017-06-19 13:42 UTC, redhatua commented on source/includes/_appendix.md
> +curl -X POST \
Should be GET

2017-06-19 13:42 UTC, redhatua commented on source/includes/_appendix.md
> +var success = request.Post("/v1/directories/all", parameters);
Should be GET

2017-06-19 13:42 UTC, redhatua commented on source/includes/_appendix.md
> +`POST https://tools.brightlocal.com/seo-tools/api/v1/directories/all`
Should be GET

2017-06-19 13:42 UTC, redhatua commented on source/includes/_appendix.md
> +`POST https://tools.brightlocal.com/seo-tools/api/v1/directories/<country>`
Should be GET

2017-06-20 09:03 UTC, redhatua approved these changes

2017-08-21 12:02 UTC, redhatua approved these changes

2017-08-21 12:02 UTC, merged