APi-44: added 'is_running' field to get gpw response
BrightLocal/ApiDocs pull request #73
Opened 2017-05-30 15:27 UTC by van-der-wolf

I made some reformatting to documentation and removed fields which doesn't exist in actual response from api

2017-07-04 14:06 UTC, redhatua commented on source/includes/_gpw.md
> +        "notify": true,
So "Yes" or just `true`?

2017-07-04 14:06 UTC, redhatua commented on source/includes/_gpw.md
> +        "is_running": false
Or "No"?

2017-07-24 14:33 UTC, ejeliot requested changes

2017-07-24 14:33 UTC, ejeliot commented on source/includes/_gpw.md
> +        "notify": true,
For consistency should be "Yes" and "No" rather than true/false but yes/no should also be accepted.

2017-08-11 09:43 UTC, van-der-wolf commented
@redhatua @ejeliot Fixed

2017-08-21 14:27 UTC, ejeliot approved these changes

2017-08-23 10:15 UTC, merged